{% set name = "aixd" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aixd-{{ version }}.tar.gz
  sha256: f74a4332acfec16cdc7b1263632ea96f6dcdf69e53a0d7b852a0c1ebccfc3fc8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - pandas >=2.1.0
    - numpy >=1.22.4
    - scipy >=1.8.1
    - scikit-learn >=0.23.0
    - plotly >=5.15
    - pytorch >=2.0.0
    - wandb
    - pytorch-lightning >=2.0.0
    - bayesian-optimization
    - python >=3.9

test:
  imports:
    - aixd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aixd.ethz.ch/
  summary: 'AIXD is your go-to toolkit for design evaluation, generation, exploration, and optimization, seamlessly blending parametric modeling with AI capabilities'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gonzalocasas
    - amaissen
